/* tslint:disable */
/* eslint-disable */
/**
 * Echo Swagger Example API
 * This is a sample server server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComSerbrodaDistanceChallengeSecurityTokenPair
 */
export interface GithubComSerbrodaDistanceChallengeSecurityTokenPair {
    /**
     * 
     * @type {string}
     * @memberof GithubComSerbrodaDistanceChallengeSecurityTokenPair
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSerbrodaDistanceChallengeSecurityTokenPair
     */
    refreshToken?: string;
}

export function GithubComSerbrodaDistanceChallengeSecurityTokenPairFromJSON(json: any): GithubComSerbrodaDistanceChallengeSecurityTokenPair {
    return GithubComSerbrodaDistanceChallengeSecurityTokenPairFromJSONTyped(json, false);
}

export function GithubComSerbrodaDistanceChallengeSecurityTokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComSerbrodaDistanceChallengeSecurityTokenPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'refreshToken': !exists(json, 'refresh_token') ? undefined : json['refresh_token'],
    };
}

export function GithubComSerbrodaDistanceChallengeSecurityTokenPairToJSON(value?: GithubComSerbrodaDistanceChallengeSecurityTokenPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'refresh_token': value.refreshToken,
    };
}

