/* tslint:disable */
/* eslint-disable */
/**
 * Distance Challenge API
 * Distance Challenge API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest
 */
export interface GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest
     */
    username?: string;
}

export function GithubComSerbrodaDistanceChallengeHandlersRegistrationRequestFromJSON(json: any): GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest {
    return GithubComSerbrodaDistanceChallengeHandlersRegistrationRequestFromJSONTyped(json, false);
}

export function GithubComSerbrodaDistanceChallengeHandlersRegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function GithubComSerbrodaDistanceChallengeHandlersRegistrationRequestToJSON(value?: GithubComSerbrodaDistanceChallengeHandlersRegistrationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'username': value.username,
    };
}

