/* tslint:disable */
/* eslint-disable */
/**
 * Distance Challenge API
 * Distance Challenge API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsUser
 */
export interface ModelsUser {
    /**
     * 
     * @type {boolean}
     * @memberof ModelsUser
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsUser
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsUser
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    username?: string;
}

export function ModelsUserFromJSON(json: any): ModelsUser {
    return ModelsUserFromJSONTyped(json, false);
}

export function ModelsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'isAdmin': !exists(json, 'is_admin') ? undefined : json['is_admin'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function ModelsUserToJSON(value?: ModelsUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'created_at': value.createdAt,
        'id': value.id,
        'is_admin': value.isAdmin,
        'updated_at': value.updatedAt,
        'username': value.username,
    };
}

