/* tslint:disable */
/* eslint-disable */
/**
 * Distance Challenge API
 * Distance Challenge API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityTokenPair
 */
export interface SecurityTokenPair {
    /**
     * 
     * @type {string}
     * @memberof SecurityTokenPair
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof SecurityTokenPair
     */
    refreshToken?: string;
}

export function SecurityTokenPairFromJSON(json: any): SecurityTokenPair {
    return SecurityTokenPairFromJSONTyped(json, false);
}

export function SecurityTokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityTokenPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'refreshToken': !exists(json, 'refresh_token') ? undefined : json['refresh_token'],
    };
}

export function SecurityTokenPairToJSON(value?: SecurityTokenPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'refresh_token': value.refreshToken,
    };
}

