/* tslint:disable */
/* eslint-disable */
/**
 * Distance Challenge API
 * Distance Challenge API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HandlersLoginRequest,
    HandlersLoginRequestFromJSON,
    HandlersLoginRequestToJSON,
    HandlersRegistrationRequest,
    HandlersRegistrationRequestFromJSON,
    HandlersRegistrationRequestToJSON,
    ModelsUser,
    ModelsUserFromJSON,
    ModelsUserToJSON,
    SecurityTokenPair,
    SecurityTokenPairFromJSON,
    SecurityTokenPairToJSON,
} from '../models';

export interface LoginRequest {
    login: HandlersLoginRequest;
}

export interface RegisterRequest {
    login: HandlersRegistrationRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * login to an account
     * Login
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SecurityTokenPair>> {
        if (requestParameters.login === null || requestParameters.login === undefined) {
            throw new runtime.RequiredError('login','Required parameter requestParameters.login was null or undefined when calling login.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlersLoginRequestToJSON(requestParameters.login),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecurityTokenPairFromJSON(jsonValue));
    }

    /**
     * login to an account
     * Login
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit): Promise<SecurityTokenPair> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * register a new account
     * Register
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ModelsUser>> {
        if (requestParameters.login === null || requestParameters.login === undefined) {
            throw new runtime.RequiredError('login','Required parameter requestParameters.login was null or undefined when calling register.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlersRegistrationRequestToJSON(requestParameters.login),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsUserFromJSON(jsonValue));
    }

    /**
     * register a new account
     * Register
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit): Promise<ModelsUser> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
